[tool.pytest.ini_options]
testpaths = ["tests"]
minversion = "6.0"
xfail_strict = true
addopts = ["--color=yes"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
ignore-init-module-imports = true
ignore = [
  "F841", # Local variable name is assigned to but never used
]

[tool.ruff.extend-per-file-ignores]
"__init__.py" = [
  "E402", # Module level import not at top of file
  "F401", # Module imported but unused
  "F403", # 'from module import *' used; unable to detect undefined names
]

[tool.coverage.report]
exclude_lines = [
  "pragma: nocover",
  "raise NotImplementedError",
  "if TYPE_CHECKING:",
]

[tool.coverage.run]
omit = ["*examples*"]
