[tool.pytest.ini_options]
testpaths = ["tests"]
minversion = "6.0"
xfail_strict = true
addopts = ["--color=yes"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
ignore-init-module-imports = true
ignore = [
  "F841", # Local variable name is assigned to but never used
]

[tool.ruff.extend-per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]

[tool.coverage.report]
exclude_lines = [
  "pragma: nocover",
  "raise NotImplementedError",
  "if TYPE_CHECKING:",
]

[tool.coverage.run]
omit = ["*examples*"]

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "pymc/_version.py"
versionfile_build = "pymc/_version.py"
tag_prefix = "v"
