name: pre-commit

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SKIP: no-commit-to-branch
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Run pre-commit on oldest supported Python version
    - uses: pre-commit/action@v3.0.0
